services:
  mcp-server:
    build: .
    container_name: mcp-fal-server
    ports:
      - "8765:8080"  # Host port 8765 -> Container port 8080
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - FAL_KEY=${FAL_KEY:-}  # Environment variable'dan al
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Log dosyaları için volume
